### ISSUE TITLE
Bit Packing / Unpacking issue

### ISSUE THREAD

**Issue by umeat** [go-restruct/restruct#27]
I'm experiencing some strange behavior from the library when specifying bit length.

```
package main
  
import (
    "fmt"
    "encoding/binary"
    "github.com/go-restruct/restruct"
)

type Type struct {
    A uint16 `struct:"uint16:12"`
    B uint16 `struct:"uint16:12"`
    C uint32 `struct:"uint32:30"`
    D uint8  `struct:"uint8:1"`
    E uint8  `struct:"uint8:5"`
    F uint8  `struct:"uint8:1"`
    G uint8  `struct:"uint8:3"`
}

func main() {
    t := Type{}
    fmt.Println(restruct.Unpack([]byte{0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}, binary.BigEndian, &t))
    fmt.Printf("%+v\n", t)
    fmt.Println(restruct.Pack(binary.BigEndian, &t))
}
```

This yields:
```
<nil>
{A:4095 B:4095 C:1073741823 D:1 E:31 F:1 G:7}
[255 255 255 255 255 255 255 240] <nil>
```

Here we _seem_ to be packing correct, but not unpacking correctly. However, if I change the last byte of the input byte array to `0x00` - it effects the field `E` correctly, but `F` is still 1 and `G` is still 7 (they should both be 0): 

```
<nil>
{A:4095 B:4095 C:1073741823 D:1 E:16 F:1 G:7}
[255 255 255 255 255 255 255 0] <nil>
```

So in this case it _seems_ to unpack incorrectly, but pack correctly.

Further to this, I'm only using `uint8:1` because bool seems to not work. If I change my attribute definitions for these to ``bool `struct:"bool"` ``, it produces the following output:

```
<nil>
{A:4095 B:4095 C:1073741823 D:false E:0 F:false G:7}
[255 255 255 255 255 255 252 0 0 0 0 0 0 0 0 0] <nil>
```

Which is very weird.

**Comment by jchv** [comment]
Interesting, I'm going to need to dig into this. Bit packing is not extensively tested; it's a relatively new feature.

As for booleans, I'm surprised to say that I don't think those are working at all. It looks like I never handle that case anywhere in restruct's decoder or encoder. That warrants another separate issue. I am not sure how that went unnoticed for so long, honestly.

**Comment by jchv** [comment]
I've created #28 to cover the issues with booleans. I think I didn't end up implementing it originally because it does raise some questions, but I think what I'll do is implement C-like behavior as the default, then try to add support for as many other things as necessary (like COM-style `VARIANT_BOOL`, where true is `~0`.)

As for the other bug, I'll look into that ASAP.

**Comment by jchv** [comment]
Hey, @umeat. I have pushed an attempt to fix the bug to master. If this fixes your problem, feel free to close this bug. Otherwise, please let me know. I added your example as a test case, and will definitely add more if we find more bugs.

**Comment by umeat** [comment]
My hero.
