### ISSUE TITLE
[Question] Dynamic field type based on another field in the same struct

### ISSUE THREAD

**Issue by hetsch** [go-restruct/restruct#41]
Hi,

first, thank you for this nice library! 

I'm currently playing around with the newly added expression syntax. What I have to achieve is having a single field `Result` in the `TestResult` struct, which should return different structs (either `ResultA` or `ResultB`) based on the value of another field `Type`, see the example code attached. I'm currently making no progress and wanted to ask you for a little push in the right direction. Please bear with me if I missed some basic stuff, because I'm more of a novice in golang.

Thank you very much!

https://play.golang.org/p/S-Q5Zc0dlwA

```golang
package main

import (
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"reflect"
	"github.com/go-restruct/restruct"
)

const (
    TYPE_A = iota
    TYPE_B
)

type ResultA struct {
    	Config uint8 `struct:"uint8"` 
}

type SubresultB struct {
	Config uint8 `struct:"uint8"`
	Number float32 `struct:"float32"`
}

type ResultB struct {
	Subresult1 SubresultB
	Subresult2 SubresultB
	Subresult3 SubresultB
}

type TestResult struct {
	Type uint8 `struct:"uint8"`
	// What I would need is a single "Result" field returning different types depending on the value "Type".
	// More or less: if Type==TYPE_A return TestResult.Result=ResultA of if Type==TYPE_B return TestResult.Result=ResultB
	
	Result ResultA `struct:"if=Type==0"` // const TYPE_A in expr would be better
	// Two fields with the same name are not allowed
	// Result ResultB `struct:"if=Type==1"` // const TYPE_B in expr would be better
}


func main() {
	restruct.EnableExprBeta()
	
	result := TestResult{}
        // data for returning ResultA
	// data, _ := hex.DecodeString("0001000000000000000000000000000000")
	// data for returning ResultB
	data, _ := hex.DecodeString("010133330542023333854203cdccc742")

	err := restruct.Unpack(data, binary.LittleEndian, &result)

	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(reflect.TypeOf(result.Result).String())
	fmt.Println(result)
}
```

**Comment by jchv** [comment]
Hi! I'll try to remember to check this out again later today, but some tips:

Firstly, if you want the type to vary, you'll need to decide how you wish to handle it on the Go side. Having multiple fields with different names is a totally valid option, even if it is not pretty. Keep in mind that no matter what you do, code that needs to be able to support all of the different possible types will still need to handle switching on them somehow; this is just a limitation of static typing.

Another possible approach to type switching would be to use an `interface{}` (empty interface) type, which is the Go equivalent to say, `any` in TypeScript or `void *` in C and C++. However, Restruct does not contain special support for typeswitching for `interface{}` types, so you will need to do some things manually here; this can be done by implementing the [`restruct.Unpacker`](https://godoc.org/github.com/go-restruct/restruct#Unpacker) et al. interfaces in your types, for example. Even after doing this, you will need to use typeswitching to access the `interface{}`, switching on each struct type that is possible, so this doesn't make it more convenient or typesafe than just using multiple fields with different names.

Secondly, if you are mostly interested in just deserialization, I would like to also mention the existence of Kaitai Struct. It is a different approach than Restruct by a long shot, but it is fairly good at describing complex binary formats, and I've also contributed to their Go support a little as well (Not everything is supported, but the main important bits are - it is probably a bit more capable than Restruct.) The main difference in the approach is that it takes a YAML manifest describing the format and generates code in your language of choice, whereas Restruct uses reflection. One downside for Go is that the Kaitai Struct compiler is not written in Go but Scala, so you need the JVM or a JavaScript interpreter (like Node.JS) to run the Kaitai compiler to locally update your generated Go code when you update your Kaitai Struct manifest. But on the upside, it should perform better than Restruct at runtime. (Right now it mostly only supports deserializing data into structures, although in the future it should support seralization as well - it's just not implemented yet.)

**Comment by hetsch** [comment]
Nice answer and your tips clarify some things for me. Thank's a bunch! Funny that you mention Kaitai Struct - I've been there but the lack of serialization brought me to your library. You also make a point with me not knowing enough about static typed languages - I'm coming from Python land and used the Construct library for declarative binary parsing so far (supports `EmbeddedSwitch` the thing that I want to mimic with your library). 

I will definetly have a look at your `restruct.Unpacker` suggestion and keep learning some basic golang stuff. If you would have the time to check this out later today, it would be awesome!

**Comment by hetsch** [comment]
Half baked, but this what I have right now ...

https://play.golang.org/p/cL2elJh7RX9

```golang
type TestResult struct {
	Type   uint8       `struct:"uint8"`
	Result interface{} `stuct:"interface{}"`
}

func (s *TestResult) Unpack(buf []byte, order binary.ByteOrder) ([]byte, error) {
	var t uint8
	var bufOffset int
	err := restruct.Unpack(buf, order, &t)
	if err != nil {
		return buf, errors.New("Not a known test result type")
	}
	bufOffset += 1

	var result interface{}

	switch t {
	case TYPE_A:
		result = ResultA{}
		err = restruct.Unpack(buf[bufOffset:], order, &result)
	case TYPE_B:
		result = ResultB{}
		err = restruct.Unpack(buf[bufOffset:], order, &result)
	default:
		err = errors.New("Not a know test result type")
	}

	if err != nil {
		return buf, err
	}

	s.Type = t
	s.Result = result

	resOffset, err := restruct.SizeOf(result)
	if err != nil {
		return buf, errors.New("Could not get the size of the result struct")
	}

	bufOffset += resOffset

	if bufOffset >= len(buf) {
		return []byte{}, nil
	} else {
		return buf[bufOffset:], nil
	}
}
```

**Comment by jchv** [comment]
That looks about right. I am doing something similar sometimes but using reflection magic to use a map to empty structs instead of a switch case.

The main issue you have here is that you are trying to unpack into a pointer to an interface to a value type, which does not work. Pointer to interface doesn't usually make sense. Interface directly will silently fail because it will fail to get a mutable value. Interface with pointer makes a bit more sense, and Restruct will happily unpack to that.

I modified a couple of other things to try to make it a little more succinct, but if you just swap where the reference operator is placed it will start working.

https://play.golang.org/p/N_qZgUC8u2Y

**Comment by hetsch** [comment]
Thank you so much for your help! The improvements of yours are very welcome and make total sense. May I ask you about the implementation of the reflection magic that you mentioned in your first sentence. I close the ticket now because everything I asked is more than answered.
